update task ingredient amounts
mayanb/wafflecone pull request #139
Opened 2018-04-24 22:53 UTC by mayanb

2018-04-25 00:52 UTC, sguichard commented on ics/v9/serializers.py
> +			matching_task_ings.update(actual_amount=F('actual_amount') + new_input.input_item.amount)
In the case where there's a recipe, should we just set the TaskIngredient actual_amount to the scaled_amount?

2018-04-25 20:39 UTC, ishitap commented on ics/v9/serializers.py
> +			matching_task_ings.update(actual_amount=F('actual_amount') + new_input.input_item.amount)
Yes I thought that was the plan

2018-04-25 20:39 UTC, ishitap commented on ics/v9/serializers.py
> +			matching_task_ings.update(actual_amount=F('actual_amount') + new_input.input_item.amount)
So you only need to edit it when u do something different

2018-04-26 18:22 UTC, ishitap requested changes
plz comment bc complicated

2018-04-26 18:51 UTC, ishitap approved these changes
It's fine for now, but we should put constraints in places and enforce things like only 1 ingredient for a particular proc/prod/recipe etc.

2018-04-26 18:52 UTC, merged