Make Process.icon editable (for Edit process icon frontend change)
mayanb/wafflecone pull request #166
Opened 2018-05-11 21:00 UTC by davidnmora

Corresponding front-end change:
https://github.com/polymerteam/snickerdoodle/pull/232

2018-05-11 21:38 UTC, mayanb requested changes

2018-05-11 21:38 UTC, mayanb commented on ics/v10/serializers.py
> +	icon = serializers.CharField()
if you aren't specifying anything special about icon you actually don't need this line at all

2018-05-14 19:46 UTC, davidnmora commented on ics/v10/serializers.py
> +	icon = serializers.CharField()
Ahhh, makes sense! Stuff need only be specified up here if we're doing something special, like formatting or setting it to be read-only

2018-05-15 00:42 UTC, mayanb approved these changes

2018-05-15 01:25 UTC, merged