Don't allow duplicate goals
mayanb/wafflecone pull request #179
Opened 2018-06-02 01:49 UTC by davidnmora

❌ to newly created duplicate goals

2018-06-02 18:18 UTC, mayanb requested changes

2018-06-02 18:18 UTC, mayanb commented on ics/v10/serializers.py
> +		possible_duplicates = Goal.objects.filter(is_trashed=False,
we should probably also filter by whether it's using all_product_types as well and if it is, then we don't even need to do the product type check - we can stop before adding that filter (especially since in the past i think we were creating goals that had all product types by actually making goalproducttypes for them)

2018-06-02 18:18 UTC, mayanb commented on ics/v10/serializers.py
> +		annotated_possible_duplicates = possible_duplicates.annotate(
we should also check that the length of the product type array is the same s the length of arr because right now if we're looking for product types [1,2,3] and we see a goal that has [1,2,3,4,5] it's going to return it as a match

2018-06-04 20:10 UTC, davidnmora commented on ics/v10/serializers.py
> +		possible_duplicates = Goal.objects.filter(is_trashed=False,
On it!

2018-06-04 20:10 UTC, davidnmora commented on ics/v10/serializers.py
> +		annotated_possible_duplicates = possible_duplicates.annotate(
oooh, great catch! I fixed this and tested for it, so we should be good to go.

2018-06-04 20:22 UTC, mayanb requested changes

2018-06-04 20:22 UTC, mayanb commented on ics/v10/serializers.py
> +			for duplicate in duplicates.all():
how about instead we can do it in a one liner type thing instead of having to iterate? so it is making the comparison directly in the db query?
queryset.annotate(count=Count('goal_product_types__product_type__id')).values_list('id', 'arr', 'count').filter(query).filter(count=whatever_the_length_of_product_types_is)

2018-06-05 00:43 UTC, davidnmora commented on ics/v10/serializers.py
> +			for duplicate in duplicates.all():
Totally! Thanks for that -- I actually spent a fair bit of time looking for a way to get the length of the array, and didn't realize there was a `Count` fn.

Is there a reason you include 'id' in the values list? It seems we only use `arr` and `count`.

2018-06-05 22:41 UTC, mayanb approved these changes

2018-06-06 01:02 UTC, merged