Display inventory items cost backend
mayanb/wafflecone pull request #214
Opened 2018-07-26 22:56 UTC by ScarpMetal

Do not review until PR https://github.com/polymerteam/wafflecone/pull/210 is merged into the cogs branch. 

The changes in this PR are used in order to display aggregate cost totals on the inventory screen. It would be very helpful if someone could closely review my queries and see if there is a more efficient way of accessing this data. There are some weird nuances to aggregating cost when there are inventory adjustments, so the solution was no obvious to me.

2018-07-28 12:28 UTC, mayanb commented on ics/v11/queries/inventory.py
> +	for item in items:
https://stackoverflow.com/questions/43517901/cumulative-running-sum-with-django-orm-and-postgresql
^i think we're trying to do something like this where we have a cumulative sum on the item's amount and we are partitioning on that amount - there seems to be a way here to do that in a single django query; not sure if you've already seen/tried this.
also im assuming this is an initial version and we will be updating the value of an inventory unit later to include the cost of creating minus the cost used?

2018-07-28 12:32 UTC, mayanb commented on ics/v11/serializers.py
> +	def get_product_types(self, item_summary):
if we're using this same exact function in multiple places we should probably pull it out

2018-07-31 21:59 UTC, ScarpMetal commented on ics/v11/serializers.py
> +	def get_product_types(self, item_summary):
Do you think it would be worth it to have both InventoryList2 and InventoryList2Aggregate (views.py) both use InventoryList2Serializer (rather than each having their own)?

2018-08-06 21:18 UTC, mayanb commented on ics/v11/queries/inventory.py
> +				Sum('creating_task__cost'),
we should use the cost field we defined earlier here so that later we can edit the cost field to be creating cost - remaining cost and we only have to change it in that one place

2018-08-06 21:22 UTC, mayanb commented on ics/v11/queries/inventory.py
> +				Sum('creating_task__cost'),
we also need to handle the case here where the cost is null- right now it's going to break.

2018-08-06 21:48 UTC, mayanb requested changes
this currently breaks if any cost is null

2018-08-07 17:00 UTC, mayanb commented on ics/v11/queries/inventory.py
> +	#total_cumulative_cost = item.cumulative_cost + item.cumulative_cost_offset
can we remove this line?

2018-08-07 17:00 UTC, mayanb approved these changes

2018-08-07 20:52 UTC, merged