Display Image Previews Backend
mayanb/wafflecone pull request #221
Opened 2018-08-13 21:41 UTC by ScarpMetal

Changes to the backend were made so that a list of files would be returned with a task. We might also need to merge some migrations after COGS is merged because I separated the name field into name and extension fields.

2018-08-15 20:24 UTC, mayanb requested changes

2018-08-15 20:24 UTC, mayanb commented on ics/models.py
> +	extension = models.CharField(max_length=10, null=True)
how does this deal with files that have been already uploaded and therefore don't have an extension? do you need to write a command to migrate them properly?

2018-08-17 19:45 UTC, ScarpMetal commented on ics/models.py
> +	extension = models.CharField(max_length=10, null=True)
Command written! The name field will now be separated out into name and extension fields.

2018-08-17 20:05 UTC, mayanb approved these changes

2018-08-17 20:13 UTC, merged