Production planning backend
mayanb/wafflecone pull request #224
Opened 2018-08-27 19:03 UTC by ScarpMetal

Backend for all things related to the production planning dashboard.

2018-08-27 20:03 UTC, mayanb commented on ics/v11/queries/production_planning.py
> +	level = 0
why do we need this variable if we're not using it for anything?

2018-08-27 20:04 UTC, mayanb commented on ics/v11/queries/production_planning.py
> +	for pathKey in paths:
i don't think we need to calculate the conversion rate for every single ingredient type - we should do it on the fly only for the ones we actually care about

2018-08-27 20:04 UTC, mayanb commented on ics/v11/queries/production_planning.py
> +def get_conversion_rates(conversion_map, source):
if you referenced code from another library that you're not importing, make sure to cite that in a comment :)

2018-08-27 20:12 UTC, mayanb commented on ics/v11/queries/production_planning.py
> +	for pathKey in paths:
also can we calculate the rates while we're generating the path?

2018-08-27 20:18 UTC, mayanb commented on ics/v11/serializers.py
> +		timeElapsed = timedelta(days=30).total_seconds()
you should make this time period a constant since it needs to be the same one you used when calculating the amount used in the queryset - right now someone could inadvertently change one of these numbers in one place and it would make things incorrect

2018-08-27 20:22 UTC, mayanb commented on ics/v11/views.py
> +      ancestorProducts = []
isn't this going to mean if we use the ingredients R-MM16 and L-SUG we're going to end up looking for all items including R-MM16, R-SUG, L-MM16 and L-SUG which isn't what we want?

2018-08-27 20:23 UTC, mayanb commented on ics/v11/views.py
> +      ancestorProcesses = []
if we're reusing code we should pull it out into a separate function

2018-08-27 20:23 UTC, mayanb requested changes
see comments

2018-08-27 21:27 UTC, mayanb commented on ics/v11/queries/production_planning.py
> +				conversion_rate = batch_size / ti.actual_amount
need to check if actual amount is 0 before diving by it

2018-08-27 22:04 UTC, mayanb commented on ics/v11/serializers.py
> +	def get_can_make(self, item_summary):
if the adjusted_item_amount is negative, you should cap can_make at 0 rather than telling them they can make a negative amount

2018-08-27 23:29 UTC, mayanb commented on ics/v11/serializers.py
> +		amount = get_adjusted_item_amount(process_type, product_type)
should return get_adjusted_item_amount for each item as part of the queryset returned by the view

2018-08-27 23:30 UTC, mayanb commented on ics/v11/views.py
> +    return queryset
add this code after
```
    returnobj = []
    for x in queryset:
      proc = x['creating_task__process_type']
      prod = x['creating_task__product_type']
      amt = x['amount_used']
      adj_amt = get_adjusted_item_amount(proc, prod)
      returnobj.append({'creating_task__process_type': proc, 'creating_task__product_type': prod, 'amount_used': amt, 'adj_amt': adj_amt})
    return returnobj

2018-08-27 23:30 UTC, mayanb commented on ics/v11/views.py
> +        ancestors = sampleTask.ancestors().filter(process_type__category=ancestor_category)
we shouldn't have to do this here if we're already doing this to make the conversion map - when we're going through the conversion map we can get the key's that have the process type in the category we want

2018-08-29 21:50 UTC, ScarpMetal commented on ics/v11/views.py
> +      ancestorProducts = []
Removed this part in the current implementation

2018-08-29 21:52 UTC, ScarpMetal commented on ics/v11/queries/production_planning.py
> +	level = 0
removed

2018-08-30 17:55 UTC, mayanb commented on ics/v11/queries/production_planning.py
> +	if not source in conversion_map:
can we break this up into shorter helper functions? maybe 1 to get all the shortest paths and another to build up the queryset info list and one to calculate the conversion rate and the amount used

2018-08-30 17:55 UTC, mayanb commented on ics/v11/queries/production_planning.py
> +	selected_process_type = source[0]
what are these 2 variables being used for?

2018-08-30 18:01 UTC, ScarpMetal commented on ics/v11/queries/production_planning.py
> +	selected_process_type = source[0]
Oh I think I might have been using them in an earlier implementation, but I can remove them now

2018-08-31 17:11 UTC, mayanb commented on ics/v11/serializers.py
> +		dateExhausted = self.get_date_exhausted(item_summary)
![image](https://user-images.githubusercontent.com/7052505/44926390-1a73b600-ad06-11e8-8aa1-2596ef8a415b.png)
right now this means if there's no data for a rm from the last 30 days even if there's 0 of it left in stock we're not going to get a warning. we should add more conditions to handle that

2018-09-01 00:52 UTC, ScarpMetal commented on ics/v11/serializers.py
> +		dateExhausted = self.get_date_exhausted(item_summary)
I'm confused though, because if their amount is zero and their rate of consumption is zero, then it doesn't make sense to warn them that they are going to run out. For example, if they only made B-MT once, but don't have plans to make it again, they would be perpetually warned that they are going to run out of B-MT even though they are not actively using it.

2018-09-01 01:38 UTC, mayanb commented on ics/v11/serializers.py
> +		dateExhausted = self.get_date_exhausted(item_summary)
Well I think the idea is if they’re looking at the production planning info for something that uses b-mt it’s because they want to know how much of it they can make. And if they have none of one of its ingredients on stock they should get warned about that

2018-09-04 21:36 UTC, mayanb commented on ics/v11/serializers.py
> +		fields = ('id', 'all_product_types', 'process_type', 'goal', 'actual', 'process_name', 'process_unit', 'process_icon', 'product_code', 'timerange', 'rank', 'is_trashed', 'trashed_time', 'userprofil
you probably want to remove total_inventory_amount from the fields list?

2018-09-05 20:39 UTC, mayanb approved these changes

2018-09-05 20:52 UTC, merged