Update costs
mayanb/wafflecone pull request #234
Opened 2018-09-06 16:46 UTC by davidnmora

## overview
Completes and fixes bugs/incorrect calculations of what's already merged into staging.

## input delete command: *./manage.py delete_inputs_to_and_from_deleted_tasks*
On production, when we delete a task, we just set `is_trashed=True` but leave inputs (__and therefore TaskIngredients__) untouched. Since this code now deletes inputs to/from deleted tasks, there's a command to do that for existing trashed tasks. The inputs deletions in the command will trigger the `signals.py` to also properly update the corrosponding TaskIngredient.

## front end
It also update costs when a user [changes costs on the Dashboard](https://github.com/polymerteam/snickerdoodle/pull/298)

2018-09-06 17:31 UTC, mayanb commented on ics/cost_update_helpers.py
> +def update_parents_for_ingredient_and_their_children(updated_task_id, old_amount, new_amount, process_type, product_type, creating_task_of_changed_input=-1, input_added=False, input_deleted=False, ch
it's a little strange to have input_added and input_deleted when you know it's either going to be one, the other, or neither. i think it might make more sense to have it be one parameter that is an enum (or just an int set to either -1 0 or 1)

2018-09-06 19:09 UTC, mayanb commented on ics/cost_update_helpers.py
>  			visited[child] = child
does visited need to be a dictionary? can it just be a list or set?

2018-09-06 19:26 UTC, mayanb commented on ics/cost_update_helpers.py
>  	for child in tasks[parent]['children']:
don't we have to go in the order of the children being added here as well?

2018-09-06 19:32 UTC, mayanb requested changes
+ a few other thoughts it wouldn't let me inline comment since these were previously merged into staging:

1. In ingredient_updated (task ingredient) why do we need was_amount_changed if we also have a field tracker?

2. In batch_size_update, I don’t think it’s getting the parent_previous_batch_size and parent_new_batch_size correctly - I think we need to do the same thing you’re doing in get_prev_and_new_unit_costs since the task could have more than one item so the batch size can’t just be obtained from the one item that is changing?

3. There are a few places where you’re doing x = a if a <= b else b 
It might be more clear to write this as x = min(a, b)

I’m a little confused by get_child_desired_ingredient_amount - is the child’s amount 4. guaranteed to be that? do you have to account for the fact that it might actually be receiving less than that depending on the order? Or does it not matter here since you’re capping the costs?

2018-09-06 22:07 UTC, davidnmora commented on ics/cost_update_helpers.py
>  			visited[child] = child
Haha, I think that was Aditya being new to Python. :) 
Actually, we don't even need it anymore, now that it gets `descendant(breakIfCycle=True)`. I'll remove it!

2018-09-06 22:49 UTC, davidnmora commented on ics/cost_update_helpers.py
>  	for child in tasks[parent]['children']:
Totally, thanks for catching that! I ordered the children at the point of original creation, so now they'll be in input order everywhere they're accessed.

2018-09-07 00:09 UTC, davidnmora commented
### @mayanb, to respond to/fix your 4 comments:

1. In ingredient_updated (task ingredient) why do we need was_amount_changed if we also have a field tracker?
__david__ Aditya wrote that, and I can't personally think of a better way: we set `task_ingredient.was_amount_changed=True` only when a TaskIngredient is changed in a patch request, allowing us to differentiate those intances from times we update TaskIngredient after an input change (or otherwise). __Let me know if you have a different way, or would like me to keep trying to find a different approach.__

2. In batch_size_update, I don’t think it’s getting the parent_previous_batch_size and parent_new_batch_size correctly - I think we need to do the same thing you’re doing in get_prev_and_new_unit_costs since the task could have more than one item so the batch size can’t just be obtained from the one item that is changing?
__david__ Great catch -- I *am* forgetting to account for multiple items. Fixed!

3. There are a few places where you’re doing x = a if a <= b else b 
It might be more clear to write this as x = min(a, b)
__david__ Hah, so much simpler! Changed them all to x = min/max(a, b)

4. I’m a little confused by get_child_desired_ingredient_amount - is the child’s amount  guaranteed to be that? do you have to account for the fact that it might actually be receiving less than that depending on the order? Or does it not matter here since you’re capping the costs?
__david__ Yes, we cap the costs. To clarify: `get_child_desired_ingredient_amount` returns the uncapped the amount a child would like to receive, which we cap at the amount still available in the parent. Here's the code:
```python
return float(min(parent_remaining_batch_size, child_desired_ingredient_amount))
```

2018-09-12 18:07 UTC, davidnmora commented on ics/cost_update_helpers.py
> +def update_parents_for_ingredient_and_their_children(updated_task_id, old_amount, new_amount, process_type, product_type, creating_task_of_changed_input=-1, input_added=False, input_deleted=False, ch
Totally agree. At this point, the amount of code changed and possibility of introducing bugs is probably not worth the re-factor. I'm happy to do it though if you feel strongly.

2018-09-19 00:47 UTC, mayanb approved these changes

2018-09-19 01:24 UTC, merged